export {default as apps} from "./apps_deve.png"
export {default as disens} from "./disens.svg"
export {default as markiting} from "./markiting.svg"
export {default as web_deve} from "./web_deve.svg"
export {default as web_deve2} from "./web_deve2.png"